"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const MainContainer = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
`;

const Container = styled.div`
    @media (width < 768px) {
        min-width: 320px;
        background-color: red;
    }
    @media (width >= 768px) {
        width: 1200px;
        height: 700px;
        margin-top: 100px;
        background-color: blue;
    }
    @media (width >= 1250px) {
        width: 1200px;
        height: 700px;
        margin-top: 100px;
        background-color: green;
    }
    border: 1px solid white;
    display: flex;
    justify-content: center;
    flex-direction: column;
    gap: 10px;
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MainContainer>
                    <Container>{children}</Container>
                </MainContainer>
            </body>
        </html>
    );
}
